version: "3"
networks:
  quarkus-vs-spring:
    driver: bridge

services:
  demo-quarkus:
    image: demo-quarkus:0.0.1
    container_name: demo-quarkus
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      -  quarkus-vs-spring
  demo-spring:
    image: demo-spring:0.0.1
    container_name: demo-spring
    ports:
      - 8081:8081
    expose:
      - 8081
    networks:
      -  quarkus-vs-spring